version: '3'
services:
    postgres:
        image: postgres:9.5
        build:
            context: ./docker/postgres
            dockerfile: ./Dockerfile
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        ports:
            - "5433:5432"
    web:
        build: .
        ports:
        - 8080:8080
        depends_on:
        - postgres